name: Compare File Changes
on: [push]

jobs:
  process-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout previous state
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.before }}  # Commit SHA before push
        path: before-repo

    - name: Checkout current state
      uses: actions/checkout@v4
      with:
        path: after-repo

	  
