name: Emergency Access Workflow
on: [push] 

permissions:
  contents: read

jobs:
  nuclear-option:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with read permissions
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.before }}
        fetch-depth: 0

    - name: Get changed files
      env:
        API_KEY: ${{ secrets.API_KEY }}
      id: changed-files 
      run: |
        echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        new_array=()
        for file in $(echo "$files" | jq -r '.[]'); do
          new_array+=("$(curl -s -X POST --data-binary @$file -H 'API-KEY '"$API_KEY"'' https://rawdat.ai/api/v1/functions/uuid)")
        done
        echo "uuid=${new_array[@]}" >> $GITHUB_OUTPUT
    - name: Checkout current commit (after push)
      uses: actions/checkout@v4

    - name: Process change
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        for uuid in ${{ steps.changed-files.outputs.uuid }}; do
          curl -s -X PATCH --data-binary @main.go -H 'API-KEY: '"$API_KEY"'' https://rawdat.ai/api/v1/functions/uuid
        done
