name: Compare File Changes
on: [push]

jobs:
  analyze-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout previous commit
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.before }}  # Commit SHA before push
        path: before

    - name: Checkout current commit
      uses: actions/checkout@v4
      with:
        path: after

    - name: Get changed files
      id: changed-files
      run: |
        cd before
        git ls-tree -r --name-only HEAD > before.txt
        cd ../after
        git ls-tree -r --name-only HEAD > after.txt
        cd ../
        
        echo "files=$(comm -12 <(sort before/before.txt) <(sort after/after.txt) | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

    - name: Compare file content
      run: |
        for file in $(echo '${{ steps.changed-files.outputs.files }}' | jq -r '.[]'); do
          echo "Comparing $file"
          diff -u before/$file after/$file || true
        done

