name: Emergency Access Workflow
on: [push] 

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  nuclear-option:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with full permissions
      uses: actions/checkout@v4
      with:
        # Bypass all caches and history issues
        fetch-depth: 0
        ref: ${{ github.sha }}

    - name: Validate repository access
      run: |
        echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        echo $files

