name: Process File Changes
on: [push]

jobs:
  process-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout previous state
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.before }}
        path: before-repo
        fetch-depth: 0

    - name: Checkout current state
      uses: actions/checkout@v4
      with:
        path: after-repo

    - name: Debug commit
      run: |
        git fetch --depth=1 origin ${{ github.sha }}
        git show ${{ github.sha }}  # Replace with your SHA if hardcoded

