name: Process File Changes
on: [push]

jobs:
  process-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout previous state
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.before }}
        path: before-repo

    - name: Checkout current state
      uses: actions/checkout@v4
      with:
        path: after-repo

    - name: Get changed files
      id: changed-files
      run: |
        echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | jq -R -s -c 'split("\n")[:-1]')"
        echo $files
