name: Compare File Changes
on: [push]

jobs:
  process-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout previous state
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.before }}  # Commit SHA before push
        path: before-repo

    - name: Checkout current state
      uses: actions/checkout@v4
      with:
        path: after-repo

    - name: Get changed files
      id: changed-files
      run: |
        echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        
    - name: Retrieve uuids from changed functions
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
      echo '${{ steps.changed-files.outputs.files }}' | jq -r '.[]' | while read -r file; do
        #Get before content (base64 encoded)
        if [ -f "before-repo/$file" ]; then
	  BEFORE=$(base64 -w0 "before-repo/$file")
        else
          BEFORE="null"
	fi
	  #POST before content to the API
	  curl -s -X POST --data-binary $BEFORE -H 'API-KEY: $API_KEY' "https://rawdat.ai/api/v1/functions/uuid"         
        done
	  
